# Generated by Django 4.1.6 on 2023-02-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulename', models.CharField(blank=True, db_column='RuleName', max_length=1000, null=True)),
                ('ruleid', models.CharField(blank=True, db_column='RuleId', max_length=500, null=True)),
                ('lastmodifiedutc', models.CharField(blank=True, db_column='lastModifiedUtc', max_length=100, null=True)),
                ('falsepositives', models.IntegerField(blank=True, db_column='FalsePositives', null=True)),
                ('undetermined', models.IntegerField(blank=True, db_column='Undetermined', null=True)),
                ('benignpositives', models.IntegerField(blank=True, db_column='BenignPositives', null=True)),
                ('truepositives', models.IntegerField(blank=True, db_column='TruePositives', null=True)),
                ('activeincedents', models.IntegerField(blank=True, db_column='ActiveIncedents', null=True)),
                ('newincedents', models.IntegerField(blank=True, db_column='NewIncedents', null=True)),
                ('severity_informational', models.IntegerField(blank=True, db_column='Severity.Informational', null=True)),
                ('severity_low', models.IntegerField(blank=True, db_column='Severity: Low', null=True)),
                ('severity_medium', models.IntegerField(blank=True, db_column='Severity: Medium', null=True)),
                ('severity_high', models.IntegerField(blank=True, db_column='Severity: High', null=True)),
                ('frequency', models.IntegerField(blank=True, db_column='Frequency', null=True)),
                ('annualizedfrequency', models.DecimalField(blank=True, db_column='annualizedFrequency', decimal_places=0, max_digits=10, null=True)),
                ('fidelity', models.DecimalField(blank=True, db_column='Fidelity', decimal_places=0, max_digits=10, null=True)),
                ('recoveryvalue', models.IntegerField(blank=True, db_column='RecoveryValue', null=True)),
                ('annualizedrecoveryvalue', models.IntegerField(blank=True, db_column='AnnualizedRecoveryValue', null=True)),
                ('param_starttime', models.CharField(blank=True, db_column='param_startTime', max_length=100, null=True)),
                ('param_endtime', models.CharField(blank=True, db_column='param_endTime', max_length=100, null=True)),
                ('param_infosevcost', models.IntegerField(blank=True, db_column='param_infoSevCost', null=True)),
                ('param_lowsevcost', models.IntegerField(blank=True, db_column='param_lowSevCost', null=True)),
                ('param_medsevcost', models.IntegerField(blank=True, db_column='param_medSevCost', null=True)),
                ('param_highsevcost', models.IntegerField(blank=True, db_column='param_highSevCost', null=True)),
                ('average_severity', models.IntegerField(blank=True, db_column='Average Severity', null=True)),
                ('average_impact_cost', models.IntegerField(blank=True, db_column='Average Impact Cost', null=True)),
            ],
            options={
                'db_table': 'alert_summary_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiemoptSiemopt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('completed', models.IntegerField()),
            ],
            options={
                'db_table': 'siemopt_siemopt',
                'managed': False,
            },
        ),
    ]
