# Generated by Django 4.1.6 on 2023-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siemopt', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionVolumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('sourcesystem', models.TextField(blank=True, db_column='SourceSystem', null=True)),
                ('billable', models.TextField(blank=True, null=True)),
                ('daily_entries', models.IntegerField(blank=True, null=True)),
                ('daily_datasize_gb', models.FloatField(blank=True, db_column='daily_datasize_GB', null=True)),
                ('daily_ingestion_cost', models.FloatField(blank=True, null=True)),
                ('daily_retention_cost', models.FloatField(blank=True, null=True)),
                ('daily_logging_cost', models.FloatField(blank=True, null=True)),
                ('retention_days_param_field', models.IntegerField(blank=True, db_column='Retention Days (param)', null=True)),
                ('retention_cost_param_field', models.FloatField(blank=True, db_column='Retention Cost (param)', null=True)),
                ('ingestion_cost_param_field', models.FloatField(blank=True, db_column='Ingestion Cost (param)', null=True)),
            ],
        ),
    ]
