# Generated by Django 4.1.6 on 2023-02-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siemopt', '0004_ingestionvolumedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingestionvolumedata',
            options={'managed': False},
        ),
    ]
